/**
 * Bambu Studio / Orca Slicer serializer.
 *
 * Translates a resolved parameter map into a valid `.3mf` archive.
 * The archive contains process, filament, and printer profile JSON files
 * compatible with Bambu Studio and Orca Slicer's config bundle import.
 *
 * Used for: Bambu Lab A1 Mini, Bambu Lab X1C, Creality K1.
 *
 * The `.3mf` format is a ZIP archive. This serializer uses `fflate` to create
 * a store-mode ZIP (no compression — files are small JSON).
 *
 * Key mapping decisions (internal → Bambu/Orca):
 *   printSpeed          → inner_wall_speed
 *   externalPerimeterSpeed → outer_wall_speed
 *   perimeterCount      → wall_loops
 *   topSolidLayers      → top_shell_layers
 *   bottomSolidLayers   → bottom_shell_layers
 *   infillDensity       → sparse_infill_density with "%" suffix
 *   infillPattern       → sparse_infill_pattern
 *   supportEnabled      → enable_support ("1"/"0")
 *   fanKickInLayer      → close_fan_the_first_x_layers
 *   bedSizeX/Y          → printable_area (four corner coordinate strings)
 *
 * Filament profile values are arrays (even for single-extruder) to match
 * the OrcaSlicer preset JSON schema.
 *
 * Physical import validation (AC: "importing does not produce an error") is a
 * manual gate in S-5.6 — it cannot be verified programmatically.
 */

import { zipSync, strToU8 } from 'fflate';
import type { ResolvedParams } from '../engine/types';
import type { Combination } from '../../src/types';

/** Maps an internal infill pattern name to an OrcaSlicer sparse_infill_pattern value. */
function mapInfillPattern(pattern: string): string {
  const mapping: Record<string, string> = {
    gyroid: 'gyroid',
    honeycomb: 'honeycomb',
    lines: 'zig-zag',
    grid: 'grid',
    triangles: 'triangles',
  };
  return mapping[pattern] ?? 'gyroid';
}

/** Derives the filament_type string from the material ID. */
function mapFilamentType(materialId: string): string {
  const mapping: Record<string, string> = {
    pla: 'PLA',
    petg: 'PETG',
    tpu: 'TPU',
  };
  return mapping[materialId] ?? materialId.toUpperCase();
}

/**
 * Builds the process profile JSON object.
 *
 * Layer heights and speeds use string representation as required by OrcaSlicer.
 * The "type" field identifies this as a process profile to the slicer.
 */
function buildProcessProfile(
  params: ResolvedParams,
  combination: Combination,
): Record<string, unknown> {
  const name = `PrintHub - ${combination.slug} - process`;

  return {
    type: 'process',
    setting_id: `user_${combination.slug}_process`,
    name,
    from: 'User',
    is_custom_defined: '1',
    layer_height: String(params['layerHeight']),
    initial_layer_height: String(params['firstLayerHeight']),
    line_width: String(params['lineWidth']),
    wall_loops: String(params['perimeterCount']),
    top_shell_layers: String(params['topSolidLayers']),
    bottom_shell_layers: String(params['bottomSolidLayers']),
    sparse_infill_density: `${params['infillDensity']}%`,
    sparse_infill_pattern: mapInfillPattern(params['infillPattern'] as string),
    enable_support: params['supportEnabled'] ? '1' : '0',
    outer_wall_speed: String(params['externalPerimeterSpeed']),
    inner_wall_speed: String(params['printSpeed']),
    initial_layer_speed: String(params['firstLayerSpeed']),
    infill_speed: String(params['infillSpeed']),
    travel_speed: String(params['travelSpeed']),
    max_volumetric_speed: String(params['maxVolumetricSpeed']),
    seam_position: 'aligned',
    reduce_infill_retraction: '1',
    notes: 'Generated by PrintHub',
  };
}

/**
 * Builds the filament profile JSON object.
 *
 * Values are arrays per the OrcaSlicer multi-material preset schema.
 * Single-extruder printers always have arrays of length 1.
 */
function buildFilamentProfile(
  params: ResolvedParams,
  combination: Combination,
): Record<string, unknown> {
  const name = `PrintHub - ${combination.slug} - filament`;
  const filamentType = mapFilamentType(combination.material);

  return {
    type: 'filament',
    setting_id: `user_${combination.slug}_filament`,
    name,
    from: 'User',
    is_custom_defined: '1',
    filament_type: [filamentType],
    filament_colour: ['#FFFFFF'],
    nozzle_temperature: [String(params['nozzleTemp'])],
    nozzle_temperature_initial_layer: [String(params['firstLayerNozzleTemp'])],
    bed_temperature: [String(params['bedTemp'])],
    bed_temperature_initial_layer: [String(params['firstLayerBedTemp'])],
    fan_max_speed: [String(params['fanSpeed'])],
    fan_min_speed: [String(params['fanSpeedMin'])],
    close_fan_the_first_x_layers: [String(params['fanKickInLayer'])],
    retraction_length: [String(params['retractLength'])],
    retraction_speed: [String(params['retractSpeed'])],
    deretraction_speed: [String(params['deretractSpeed'])],
    filament_density: ['1.24'],
    filament_cost: ['0'],
    reduce_fan_stop_start_freq: ['1'],
  };
}

/**
 * Builds the machine profile JSON object.
 *
 * printable_area is a list of four coordinate strings: top-left, top-right,
 * bottom-right, bottom-left.
 * firmwareFlavor is not emitted — the machine profile encodes this internally
 * in Bambu/Orca format (per parameter-schema.md).
 */
function buildMachineProfile(
  params: ResolvedParams,
  combination: Combination,
): Record<string, unknown> {
  const name = `PrintHub - ${combination.slug} - machine`;
  const x = params['bedSizeX'] as number;
  const y = params['bedSizeY'] as number;

  return {
    type: 'machine',
    setting_id: `user_${combination.slug}_machine`,
    name,
    from: 'User',
    is_custom_defined: '1',
    printable_area: [`0x0`, `${x}x0`, `${x}x${y}`, `0x${y}`],
    printable_height: String(params['maxPrintHeight']),
    nozzle_diameter: [String(params['nozzleDiameter'])],
    machine_max_speed_x: [String(params['maxSpeed'])],
    machine_max_speed_y: [String(params['maxSpeed'])],
    machine_max_acceleration_x: [String(params['maxAcceleration'])],
    machine_max_acceleration_y: [String(params['maxAcceleration'])],
  };
}

/** XML template for [Content_Types].xml — required by the Open Packaging spec. */
const CONTENT_TYPES_XML = `<?xml version="1.0" encoding="UTF-8"?>
<Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types">
  <Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/>
  <Default Extension="json" ContentType="application/json"/>
  <Default Extension="xml" ContentType="application/xml"/>
</Types>`;

/** XML template for _rels/.rels — required by the Open Packaging spec. */
const RELS_XML = `<?xml version="1.0" encoding="UTF-8"?>
<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">
</Relationships>`;

/**
 * Serializes a resolved parameter map into a Bambu Studio / Orca Slicer
 * `.3mf` config bundle archive.
 *
 * The archive is a ZIP containing three JSON profile files plus the required
 * Open Packaging Convention metadata files. Returns a Buffer — the build
 * script writes it directly to disk.
 */
export function serialize(params: ResolvedParams, combination: Combination): Buffer {
  const processProfile = buildProcessProfile(params, combination);
  const filamentProfile = buildFilamentProfile(params, combination);
  const machineProfile = buildMachineProfile(params, combination);

  // mtime is pinned to the earliest valid ZIP date, making the archive deterministic
  // regardless of build time. fflate requires dates in range 1980–2099.
  const stamp = { mtime: new Date('1980-01-01T00:00:00Z') };
  const files = {
    '[Content_Types].xml': [strToU8(CONTENT_TYPES_XML), stamp],
    '_rels/.rels': [strToU8(RELS_XML), stamp],
    'Metadata/process.json': [strToU8(JSON.stringify(processProfile, null, 2)), stamp],
    'Metadata/filament.json': [strToU8(JSON.stringify(filamentProfile, null, 2)), stamp],
    'Metadata/machine.json': [strToU8(JSON.stringify(machineProfile, null, 2)), stamp],
  } as const;

  // level 0 = store-only (no compression) — files are small JSON; no benefit to compressing
  const zipped = zipSync(files, { level: 0 });
  return Buffer.from(zipped);
}
