/**
 * PrusaSlicer serializer.
 *
 * Translates a resolved parameter map into a valid PrusaSlicer `.ini`
 * config bundle. The bundle contains three sections: [print], [filament],
 * and [printer]. Importing it via File → Import → Import Config Bundle
 * adds all three profiles to PrusaSlicer's database.
 *
 * Used for: Prusa MK4, Creality Ender 3 V3 SE.
 *
 * Key mapping decisions (internal → PrusaSlicer):
 *   printSpeed          → perimeter_speed (inner walls and most moves)
 *   firmwareFlavor      → gcode_flavor ("marlin" → "marlin2", "klipper" → "klipper")
 *   bedSizeX/bedSizeY   → bed_shape (four corner polygon)
 *   fanKickInLayer      → disable_fan_first_layers
 *   infillPattern       → fill_pattern ("lines" → "line"; others match)
 *   infillDensity       → infill_density with "%" suffix
 *   supportEnabled      → support_material (boolean → "0"/"1")
 *
 * Invariant fields not in the parameter namespace are hardcoded to their
 * PrusaSlicer defaults. These are fields required for a valid import but
 * that have no corresponding parameter in this system.
 */

import type { ResolvedParams } from '../engine/types';
import type { Combination } from '../../src/types';

/** Maps an internal infill pattern name to a PrusaSlicer fill_pattern value. */
function mapInfillPattern(pattern: string): string {
  const mapping: Record<string, string> = {
    gyroid: 'gyroid',
    honeycomb: 'honeycomb',
    lines: 'line',
    grid: 'grid',
    triangles: 'triangles',
  };
  return mapping[pattern] ?? 'gyroid';
}

/** Maps a firmwareFlavor to a PrusaSlicer gcode_flavor value. */
function mapGcodeFlavor(flavor: string): string {
  const mapping: Record<string, string> = {
    marlin: 'marlin2',
    klipper: 'klipper',
    // "bambu" is not used in PrusaSlicer profiles; included for completeness.
    bambu: 'klipper',
  };
  return mapping[flavor] ?? 'marlin2';
}

/**
 * Builds the [print] section of a PrusaSlicer config bundle.
 *
 * Covers layer geometry, speeds, infill, shell counts, and support.
 * perimeter_speed maps to our printSpeed (inner walls + most moves).
 * solid_infill_speed mirrors infillSpeed — PrusaSlicer distinguishes
 * solid and sparse infill; we use the same speed for both.
 */
function buildPrintSection(params: ResolvedParams, profileName: string): string {
  const layerHeight = params['layerHeight'] as number;
  const firstLayerHeight = params['firstLayerHeight'] as number;
  const printSpeed = params['printSpeed'] as number;
  const firstLayerSpeed = params['firstLayerSpeed'] as number;
  const externalPerimeterSpeed = params['externalPerimeterSpeed'] as number;
  const infillSpeed = params['infillSpeed'] as number;
  const travelSpeed = params['travelSpeed'] as number;
  const infillDensity = params['infillDensity'] as number;
  const infillPattern = mapInfillPattern(params['infillPattern'] as string);
  const perimeterCount = params['perimeterCount'] as number;
  const topSolidLayers = params['topSolidLayers'] as number;
  const bottomSolidLayers = params['bottomSolidLayers'] as number;
  const supportEnabled = params['supportEnabled'] as boolean;

  return [
    `[print:${profileName}]`,
    `layer_height = ${layerHeight}`,
    `first_layer_height = ${firstLayerHeight}`,
    `perimeter_speed = ${printSpeed}`,
    `external_perimeter_speed = ${externalPerimeterSpeed}`,
    `infill_speed = ${infillSpeed}`,
    `solid_infill_speed = ${infillSpeed}`,
    `top_solid_infill_speed = ${externalPerimeterSpeed}`,
    `travel_speed = ${travelSpeed}`,
    `first_layer_speed = ${firstLayerSpeed}`,
    `infill_density = ${infillDensity}%`,
    `fill_pattern = ${infillPattern}`,
    `solid_fill_pattern = rectilinear`,
    `perimeters = ${perimeterCount}`,
    `top_solid_layers = ${topSolidLayers}`,
    `bottom_solid_layers = ${bottomSolidLayers}`,
    `support_material = ${supportEnabled ? 1 : 0}`,
    `support_material_auto = 0`,
    `seam_position = aligned`,
    `avoid_crossing_perimeters = 0`,
    `complete_objects = 0`,
    `notes = Generated by PrintHub`,
    '',
  ].join('\n');
}

/**
 * Builds the [filament] section.
 *
 * fan_always_on is set to 1 when fanSpeed > 0 (material requires cooling).
 * cooling is set to 1 to enable fan control.
 * The filament_type is derived from the material ID in the combination.
 */
function buildFilamentSection(
  params: ResolvedParams,
  combination: Combination,
  profileName: string,
): string {
  const nozzleTemp = params['nozzleTemp'] as number;
  const firstLayerNozzleTemp = params['firstLayerNozzleTemp'] as number;
  const bedTemp = params['bedTemp'] as number;
  const firstLayerBedTemp = params['firstLayerBedTemp'] as number;
  const fanSpeed = params['fanSpeed'] as number;
  const fanSpeedMin = params['fanSpeedMin'] as number;
  const fanKickInLayer = params['fanKickInLayer'] as number;
  const retractLength = params['retractLength'] as number;
  const retractSpeed = params['retractSpeed'] as number;
  const deretractSpeed = params['deretractSpeed'] as number;

  const filamentType = combination.material.toUpperCase();
  const fanAlwaysOn = fanSpeed > 0 ? 1 : 0;

  return [
    `[filament:${profileName}]`,
    `filament_type = ${filamentType}`,
    `filament_colour = #FFFFFF`,
    `temperature = ${nozzleTemp}`,
    `first_layer_temperature = ${firstLayerNozzleTemp}`,
    `bed_temperature = ${bedTemp}`,
    `first_layer_bed_temperature = ${firstLayerBedTemp}`,
    `fan_always_on = ${fanAlwaysOn}`,
    `cooling = 1`,
    `max_fan_speed = ${fanSpeed}`,
    `min_fan_speed = ${fanSpeedMin}`,
    `disable_fan_first_layers = ${fanKickInLayer}`,
    `retract_length = ${retractLength}`,
    `retract_speed = ${retractSpeed}`,
    `deretract_speed = ${deretractSpeed}`,
    `filament_cost = 0`,
    `filament_density = 0`,
    `filament_diameter = 1.75`,
    `extrusion_multiplier = 1`,
    '',
  ].join('\n');
}

/**
 * Builds the [printer] section.
 *
 * bed_shape is a four-corner polygon string: "0x0,Xx0,XxY,0xY".
 * nozzle_diameter uses the nozzle layer value.
 * max_layer_height and min_layer_height use the nozzle layer bounds.
 */
function buildPrinterSection(params: ResolvedParams, profileName: string): string {
  const bedSizeX = params['bedSizeX'] as number;
  const bedSizeY = params['bedSizeY'] as number;
  const maxPrintHeight = params['maxPrintHeight'] as number;
  const nozzleDiameter = params['nozzleDiameter'] as number;
  const maxLayerHeight = params['maxLayerHeight'] as number;
  const minLayerHeight = params['minLayerHeight'] as number;
  const maxSpeed = params['maxSpeed'] as number;
  const maxAcceleration = params['maxAcceleration'] as number;
  const firmwareFlavor = params['firmwareFlavor'] as string;
  const gcodeFlavor = mapGcodeFlavor(firmwareFlavor);

  const bedShape = `0x0,${bedSizeX}x0,${bedSizeX}x${bedSizeY},0x${bedSizeY}`;

  return [
    `[printer:${profileName}]`,
    `bed_shape = ${bedShape}`,
    `max_print_height = ${maxPrintHeight}`,
    `nozzle_diameter = ${nozzleDiameter}`,
    `max_layer_height = ${maxLayerHeight}`,
    `min_layer_height = ${minLayerHeight}`,
    `gcode_flavor = ${gcodeFlavor}`,
    `machine_max_feedrate_x = ${maxSpeed}`,
    `machine_max_feedrate_y = ${maxSpeed}`,
    `machine_max_feedrate_z = 20`,
    `machine_max_feedrate_e = 120`,
    `machine_max_acceleration_x = ${maxAcceleration}`,
    `machine_max_acceleration_y = ${maxAcceleration}`,
    `machine_max_acceleration_z = 200`,
    `machine_max_acceleration_e = 5000`,
    `machine_max_jerk_x = 10`,
    `machine_max_jerk_y = 10`,
    `machine_max_jerk_z = 0.4`,
    `machine_max_jerk_e = 2.5`,
    `machine_min_travel_rate = 0`,
    `use_firmware_retraction = 0`,
    `use_relative_e_distances = 0`,
    `retract_before_travel = 2`,
    `retract_layer_change = 0`,
    '',
  ].join('\n');
}

/**
 * Serializes a resolved parameter map into a PrusaSlicer `.ini` config bundle.
 *
 * The profile name is derived from the combination slug.
 * All three sections (print, filament, printer) use the same profile name
 * to match each other when the user selects them in PrusaSlicer.
 *
 * Physical import validation (AC: "importing does not produce an error") is a
 * manual gate in S-5.6 — it cannot be verified programmatically.
 */
export function serialize(params: ResolvedParams, combination: Combination): string {
  const profileName = `PrintHub - ${combination.slug}`;
  const header = `# Generated by PrintHub\n# Profile: ${combination.slug}\n`;

  const printSection = buildPrintSection(params, profileName);
  const filamentSection = buildFilamentSection(params, combination, profileName);
  const printerSection = buildPrinterSection(params, profileName);

  return [header, printSection, filamentSection, printerSection].join('\n');
}
